New job concept of active jobs performing actions
HEPCompSim/DistCacheSim pull request #15
Opened 2022-01-19 16:17 UTC by HerrHorizontal

With the new updates introduced in of Wrench-2.X the paradigm of jobs can be shifted from passive workloads to active objects performing actions. This enables a simplified and hopefully more performant way of simulating file caching.

2022-02-21 17:20 UTC, HerrHorizontal commented
I think this is now ready to go. I performed some sanity checks and everything looks fine.

2022-02-22 13:03 UTC, ArturAkh requested changes
Looks good!

One small change is required to compile properly with wrench (pegasus parser was removed from wrench)

2022-02-22 13:12 UTC, ArturAkh commented on sgbatch/CMakeLists.txt
>  find_library(WRENCH_PEGASUS_WORKFLOW_PARSER_LIBRARY NAMES wrenchpegasusworkflowparser)
In wrench itself,

THe following change is needed in `include/wrench.h`:

```diff
 -// Tools
-#include "wrench/tools/pegasus/PegasusWorkflowParser.h"
-
```

2022-02-22 13:41 UTC, ArturAkh approved these changes

2022-02-22 13:42 UTC, merged